name: CI/CD Discord Notification

on:
  workflow_call:
    inputs:
      workflow_run:
        required: true
        type: string
    secrets:
      CICD_DISCORD_WEBHOOK:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Workflow Run
        run: |
          echo "Workflow Run: ${{ inputs.workflow_run }}"

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.CICD_DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'discord-event-send'
